"use strict";
exports.__esModule = true;
var Movies_1 = require("./Movies");
var IMDB_1 = require("./IMDB");
var readlineSync = require('readline-sync');
var titulo;
var anio = 0;
var nacionalidad;
var genero;
var primeroAnio;
titulo = readlineSync.question('cual es el titulo? ');
primeroAnio = readlineSync.question('cual es el año? ');
nacionalidad = readlineSync.question('cual es la nacionalidad? ');
genero = readlineSync.question('cual es el genero?');
anio = parseFloat(primeroAnio);
var peliculon = new Movies_1.Movie(titulo, anio, nacionalidad, genero);
console.log(peliculon);
var cartelera = new IMDB_1.IMDB([peliculon]);
var nuevaCartelera = cartelera.obtenerlnstancialMDB("imdbBBDD.json");
nuevaCartelera.peliculas.push(peliculon);
console.log(nuevaCartelera);
